# Generated by Django 3.1 on 2020-09-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stages', '0001_initial'),
        ('user', '0001_initial'),
        ('issue', '0002_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='issue',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stage'),
        ),
    ]
