# Generated by Django 3.1 on 2020-09-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.site')),
            ],
        ),
        migrations.RemoveField(
            model_name='stage',
            name='site',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
