# Generated by Django 3.1 on 2020-09-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('drawings', '0002_auto_20200907_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingremark',
            name='remarked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='parent_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.planoption'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
