# Generated by Django 3.1 on 2020-09-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Admin'), (3, 'Architecture'), (4, 'Project Manager'), (5, 'Site Engineer'), (6, 'Sub Contractor')]),
        ),
    ]
