# Generated by Django 3.1 on 2020-09-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200908_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Admin'), (3, 'Architecture'), (4, 'Project Manager'), (5, 'Site Engineer'), (6, 'Sub Contractor'), (7, 'Sub Contractor')], default=6),
        ),
    ]
