# Generated by Django 3.1 on 2020-09-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200908_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='admin',
        ),
        migrations.CreateModel(
            name='UserOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(through='user.UserOrganisation', to='user.User'),
        ),
    ]
